### ISSUE TITLE
Invalid content was found starting with element 'block'

### ISSUE THREAD

**Issue by don-vip** [pasharm/POI_Ukraine#2]
This presets makes our integration test fail:
https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/lastCompletedBuild/testReport/

```
https://pasharm.github.io/POI_Ukraine/POI_Ukraine.xml=org.openstreetmap.josm.tools.XmlParsingException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'block'. One of '{"http://josm.openstreetmap.de/tagging-preset-1.0":chunk, "http://josm.openstreetmap.de/tagging-preset-1.0":group, "http://josm.openstreetmap.de/tagging-preset-1.0":item, "http://josm.openstreetmap.de/tagging-preset-1.0":separator}' is expected. (at line 20, column 37)
org.xml.sax.SAXParseException; lineNumber: 20; columnNumber: 37; cvc-complex-type.2.4.a: Invalid content was found starting with element 'block'. One of '{"http://josm.openstreetmap.de/tagging-preset-1.0":chunk, "http://josm.openstreetmap.de/tagging-preset-1.0":group, "http://josm.openstreetmap.de/tagging-preset-1.0":item, "http://josm.openstreetmap.de/tagging-preset-1.0":separator}' is expected.
```

**Comment by pasharm** [comment]
Element 'block' does not interfere with the work of josm. But at the same time, editing the preset code is very helpful. 
Can you make element 'block' to be ignored in the test and / or add it to https://josm.openstreetmap.de/wiki/TaggingPresets?

**Comment by pasharm** [comment]
Here is an example of a screenshot
![screenshot](https://user-images.githubusercontent.com/28259056/33227232-6fee3dd4-d1a7-11e7-8e38-5b958f04bc2a.png)

**Comment by don-vip** [comment]
We already have `group` for this purpose.

**Comment by pasharm** [comment]
If you use a `group` element instead of my `block`, a menu appears in josm that you do not need to display.
![screenshot2](https://user-images.githubusercontent.com/28259056/33245459-d1d018b4-d310-11e7-9775-9449e115d31f.PNG)

**Comment by don-vip** [comment]
simply remove it then, see #3

**Comment by pasharm** [comment]
Did not quite understand you: remove _Pull requests_ or all the same element `block`?

**Comment by don-vip** [comment]
Merge my PR to remove the unsupported block element that make our integration test fail. Thanks.
